### ISSUE TITLE
How to dump the vbios

### ISSUE THREAD

**Issue by wovnep** [KotoneShiomi/GPU-Passthrough-Nvidia-Optimus#3]
I want to know what method did you use to dump the vbios. I tried using nvflash following [this](https://gitlab.com/risingprismtv/single-gpu-passthrough/-/wikis/6%29-Preparation-and-placing-of-the-ROM-file) guide, but windows did not recognized the gpu. It was giving me code 43. 

Then I tried using your rom(I have a GTX 1650 Mobile), and it "worked".  Windows did able to recognize my second display and code 43 was gone, but Device Manager still shows my GPU as "Microsoft Basic Display Adapter", and NVIDIA installer can't detect either to install drivers.

So that's why I need to know what method did you use to dump the bios. That's the only time I even got close to using NVIDIA GPU.

**Comment by Alamputraaf** [comment]
My method to install the Nvidia Driver is using  device manager. 
1.First you have to download and extract the Nvidia Driver
2.Open the Device manager > Display Adapter > and then right click  "Microsoft Basic Display Adapter" and select Update Driver
3.After that , select "Browse for my computer Drivers.
4.Checklist the "include subfolders" and select "Let me pick from list of available driver from my computers"
5.When selected "Install from Disk" you select your nvidia driver, open and select folder "Display.Driver" and select "nvltig.inf"
6. It will loading , be patient...
7. And then you scroll the all the drivers, and select (Nvidia Geforce GTX 1650) the right driver under the GTX 1630 Driver. (i have to screenshot so you will understand correctly).
8. Finish xD. Hopefully this working with your problem.
![tutor](https://github.com/Alamputraaf/GPU-Passthrough-Nvidia/assets/69661788/4b47f025-737a-40e8-b834-7e26e159b88b)

Im know this is the dirty way to install the driver. Because i watched tutorial on youtube channel "blandman studios" he can able to install driver right way. Unlike me , i have to installed manually. My problem with this laptop or my method is everything is manual every step im follow from "PCI OVMF" arch wiki. Maybe differences between me and him is he using a script to unload and load the Nvidia GPU to the vm so the host (linux) can't able to use that again. 

From your question about how to i dump the patches bios is using GPU-Z to backup my original bios and edited through software call Bless" on linux. You can watch from Mutahar (SomeordinaryGamers) [https://www.youtube.com/watch?v=BUSrdUoedTo&t=474s](url) time at: 14:10. 

After you finish to patch edited rom. saved somewhere on libvirt directory:
my is     <rom file="/var/lib/libvirt/vbios/patch.rom"/>
you dont have to same as me, i have to make directory called vbios. 
The reeason i have to save that directory under that directory /var/lib/libvirt/ because sometimes you will get an error when start the vm, because you that patches.rom is can't be readed because that permission file. You have to chown that vgabios and chmod 777 to do that.

and then it will works.

Hopefully that answer all your question.

**Comment by wovnep** [comment]
YOU ARE A HERO. I wasted 2 weeks for this and you solved it like nothing. I was able to install drivers like you said. And I didn't even have to dump bios, your vbios worked just fine. Thank you so much, and I really appreciate that you took your time to explain it in this much detail. <3

**Comment by Alamputraaf** [comment]
You're welcome, happy to hear that from you dude, and thanks for your feedback. My apologies to not include how my method to install the nvidia driver. Maybe i should make a tutorial to setup a vm with gpu passthrough on english version xd. I have walkthrough on my youtube channel acually from 2 years ago xd but using Languange Bahasa Indonesia. Im so nervous to do this tutorial.[https://www.youtube.com/watch?v=NvtvXHOSbOU](url)

**Comment by wovnep** [comment]
Wait that's actually a good video. You went over almost everything. Even tho some people like my self can't understand the language, It's still a good video to follow along. I wish I should've found you earlier, and thank god you made the post on VFIO sub, that's how I found your repo. 



> Maybe i should make a tutorial to setup a vm with gpu passthrough on english version xd.

You should. There is not that much UP TO DATE information on how to passthough a GPU when using optimus-manager with NVIDIA. I will keep an eye on, so I can learn more from you. All the best dude. Thanks again!

**Comment by Alamputraaf** [comment]
> Wait that's actually a good video. You went over almost everything. Even tho some people like my self can't understand the language, It's still a good video to follow along. I wish I should've found you earlier, and thank god you made the post on VFIO sub, that's how I found your repo.
> 
> > Maybe i should make a tutorial to setup a vm with gpu passthrough on english version xd.
> 
> You should. There is not that much UP TO DATE information on how to passthough a GPU when using optimus-manager with NVIDIA. I will keep an eye on, so I can learn more from you. All the best dude. Thanks again!

Thank you for your suggestion and support xd. Im following you on twitter (X) my twitter username is @PutraFurqaan  .
